dummy page to show query when after each exam you have to empty marks table.

UPDATE `marks` SET `English_Marks`=0,
`Urdu_Marks`=0,
`Maths_Marks`=0,
`Science_Marks`=0,
`Hpe_Marks`=0,
`Nazira_Marks`=0,
`History_Marks`=0,
`Drawing_Marks`=0,
`Islamyat_Marks`=0,
`Computer_Marks`=0,
`Arabic_Marks`=0,
`Mutalia_Marks`=0,
`Qirat_Marks`=0,
`Pashto_Marks`=0,
`Social_Marks`=0,
`Biology_Marks`=0,
`Chemistry_Marks`=0,
`Physics_Marks`=0
